### ISSUE TITLE
Profit value only change if the user interact with other parts of Sovryn 

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#1014]
Hi,

I see that if I let the page open and do not click in other parts of Sovryn, the Profit value on lending do not change. I think the value should change without need to interact in other parts of Sovryn. 

![Captura de tela de 2021-05-03 14-04-47](https://user-images.githubusercontent.com/1178856/116908248-0b610680-ac19-11eb-9cbb-9aaebf737bd0.png)

Browser: Brave
Ubuntu

**Comment by creed-victor** [comment]
Removed ticker "realtime" profit changing because it caused other issues, it should still retrieve new profit / balance each block or does that doesn't work too?

In either case entire page will be reworked so marking this as `wontfix` and closing it right now.
Feel free to re-open if profit/balance shown is wrong
