### ISSUE TITLE
Update Open Positions/Trading History tables on Margin Trade page

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1054]
- [x] Position sizes and Unrealized P/L should include USD value
- [x] Fix asset truncation in Entry Price and Liquidation Price on screen width 1280px
- [x] Remove Interest APR column on screen size < 1280px
- [x] Change Action buttons to text links
- [x] Position Margin should show position asset value instead of percentage
- [x] Trading History Tx hashes should only show first/last 4 characters with ellipses in middle (all screen sizes)

https://xd.adobe.com/view/f742b57d-92fc-44b4-4f93-49ade24a3795-8173/

1280px width example:
![image](https://user-images.githubusercontent.com/765825/117588031-d8d37400-b118-11eb-83ad-a0c62cd20911.png)

Trading Position tx hash example on 1280px width:
![image](https://user-images.githubusercontent.com/765825/117588103-42538280-b119-11eb-9012-04eb775c71a0.png)

**Comment by tiltom** [comment]
Everything is fixed but I made some adjustments comparing to the original description:

- APR column is hidden on screen size < 1536px because the table has more space to display more important things if I hide it sooner.
- Trading History Tx hashes show first/last 5 characters and not 4 because that's the way they are shown in the design.
- I also renamed "Close Position" button to "Close" according to the design.
