### ISSUE TITLE
Origins Launchpad - Sale Day

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1124]
https://xd.adobe.com/view/26da086e-fcbd-45a0-b5f9-854628433a6f-7389/grid/

**Comment by bitcoinuser** [comment]
Hi @t-z-u could you please attach the zip files so I can see what is being designed? Thanks.

**Comment by tiltom** [comment]
Here is a branch from Origins SOV sale: https://github.com/DistributedCollective/Sovryn-frontend/tree/feat/sale/src/app/containers/SalesPage . This is mostly for inspiration since the design has changed a lot + we use Tailwind for styling now but there is an example of how to work with the "Enter access code" page.

Some info regarding the "Enter access code" page from Victor:
- When users enter "access code", it sends blockchain tx with it and mints NFT. When the NFT is in users' wallets, it allows them to go to the screen where they can buy the token.
- In the Genesis case, there were different NFTs that allowed different amounts to purchase.
- If a user already has NFT, there is no access code screen.
- But in the Genesis case, we allowed users to still open that screen from the buy screen (in case they had code to a higher tier NFT).

**Comment by tiltom** [comment]
Info from Tzu regarding the screen flow:
- If users have already engaged wallets, there will be no "Engage wallet screen".
- We don't want to show the second screen ("Enter access code") if there is no access code required (it should be the case in the second day of the Fish sale).
