### ISSUE TITLE
Need to refresh page for liquidity to leave pool after withdrawing 

### ISSUE THREAD

**Issue by t-z-u** [DistributedCollective/Sovryn-frontend#1144]

**Comment by tiltom** [comment]
The same problem was with deposits, both of the problems will be fixed in the PR.

**Comment by soulBit** [comment]
Reopening this as it still appears to be an issue on latest build - replicated by depositing liquidity into a pool, and leaving tx modal open on screen after tx confirms - new deposit does not appear in liquidity history or pool row table until page refresh (we also tested to see if it updated after pool stats refreshed, around 2 minutes)

**Comment by tiltom** [comment]
Solved in #1292 , the problem was someone changed the dependencies array of `useEffect` that calculates balances. As this was a pretty fragile and error-prone solution, I decided to add a callback on successful transactions so the balances are recalculated after every successful deposit or withdrawal.
