### ISSUE TITLE
[Proposal] Rename and move "Liquidity-mining" in the menu

### ISSUE THREAD

**Issue by john-light** [DistributedCollective/Sovryn-frontend#1167]
Currently there is a menu option "Liquidity-mining" in the Finance menu. Clicking this link will take the user to the page where they can deposit funds to become a Liquidity Provider (LP) in one of the AMM pools.

![lm-menu](https://user-images.githubusercontent.com/9424721/119398726-f15d9580-bca5-11eb-80bd-2b4747e50de2.png)

I propose two changes here:

1. Rename "Liquidity-mining" in the menu to "Market making" as it was before
2. Move this "Market making" page from under the Finance menu to the Trade menu

The reason for proposing (1) is that the page currently called "Liquidity-mining" gives users access to deposit funds and become an LP in a given AMM pool _regardless of whether or not there is an active liquidity mining campaign on that pool_. This isn't primarily a "Liquidity-mining" page; this page is, first an foremost, the page that users go to and deposit funds to become market makers in the AMM pools. Liquidity mining is secondary to this.

The reason for proposing (2) is that market making is a _trading_ activity, not a _finance_ activity. It therefore makes more sense to me for this to be under the Trade menu rather than the Finance menu.

**Comment by bitcoinuser** [comment]
Hi,

When translating to Portuguese I like (Liquidity mining). Maybe could have (Liquidity-mining) on finance menu and on Trading menu add Market making. So we have the two options.

I see that now they renamed to Yield Farm. But on Portuguese I'll keep "Liquidity-mining" because it's strange translate Yield Farm to Portuguese.

Maybe the best option to me is keep Liquidity-mining and add Market making on trading? 

![Captura de tela de 2021-05-31 21-23-39](https://user-images.githubusercontent.com/1178856/120251357-b0daba80-c257-11eb-8b3b-e7a3d26e0960.png)

**Comment by john-light** [comment]
(creating activity so the bot doesn't close the issue)
