### ISSUE TITLE
Dapp update dialog not showing correct build id

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1298]
1. build id showing is build id of currently served version, not updated one. 2. build id should be clickable and open github, commit like in the footer.

Of course it makes sense to have 2 not clickable until 1 is fixed

![image](https://user-images.githubusercontent.com/765825/121421452-16b8f780-c966-11eb-9168-778cdb950be2.png)

**Comment by ShynRou** [comment]
There seems to be no way currently to get the new commit hash. When it's displayed one should be always on the previous version, that*s also why it is broken currently.
One would need to put the new commit version in some file in the the dist directory at built time, or modify the service worker to contain it. Though since we are using workbox for the service worker the latter is not an option without some hacky solution.

My suggestions would be to remove the "Built ID: xxxx" text or we add a file containing the current version / commit hash and fetch that when the dialog is shown.

@creed-victor Any thoughts?
