### ISSUE TITLE
Reward SOV vesting issue

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1337]
Users have reported issues withdrawing SOV from LM rewards - cases:

"User is shown SOV available for withdrawal from LM rewards vesting. When they withdraw, tx fails and funds are missing from the vesting display.

 I checked with Julio and he says that it is a frontend issue, since the vesting periods havent finished."

"I tryed to get the SOV rewards from the LP and the transaction failed, now it does not appear anymore in the reward section Failed transaction: 0x25e475d59361a4b474984bfae9ec5406a5ea2f97e699d80efa6f748168ac75fb

my wallet 0x6E49e4AE7cB4b66eFD32426564b8A524A08096DA"

"0x4A2517721A21D8605B7404B01a0a33806777FafC
I had 245 SOV locked. But I dont see it in vested assets section.
Where is it?"

**Comment by creed-victor** [comment]
User called claim multiple times, 2 transactions was confirmed in same block:
1. https://blockscout.com/rsk/mainnet/tx/0xbb1d2f0c5b1d0ee504857b5e79577584c6c7373878ad2dd0ee52c74b2ace6633/token-transfers
2. https://blockscout.com/rsk/mainnet/tx/0x25e475d59361a4b474984bfae9ec5406a5ea2f97e699d80efa6f748168ac75fb/internal-transactions

1st transaction was successful and tokens were claimed, 2nd tx failed because 1st already did everything.

It's also in vested assets list under "Reward SOV"
