### ISSUE TITLE
Staking end date incorrect

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1339]
From user:

"Today (12th June)I claimed my reward SOV from the Yield Farm and it now shows up in the Current Vests part of the Bitocracy/Stake/Current Vests.  The amount looks correct but the "End Date" is showing as 04/06/2021 - 10:28:15 am GMT 

This is obviously prior to the beginning of the contract. 

Not sure if this is an interface issue or something more dramatic."

https://sovryn.freshdesk.com/a/tickets/644

**Comment by grinry** [comment]
It shows startDate instead of endDate in the table

**Comment by soulBit** [comment]
@creed-victor should the startDate not be the 12th then? or is it because they claimed part-way through the 2 week staking period, and the startDate represents the start of that staking period?

If it's the second case, then would it be possible to show startDate as the vested date (e.g. 12th June in this example)?

**Comment by grinry** [comment]
Different vest types may have different periods, now not sure if the start date is actual date user submitted it or nearest staking period snapshot.

But the issue is def start date: 
https://github.com/DistributedCollective/Sovryn-frontend/blob/3ecd727b38e200ea58e3a99ae8f578e80ed668c2/src/app/containers/StakePage/components/VestingContract.tsx#L210

I think wrong column was deleted when fee-sharing column was added.
