### ISSUE TITLE
Check closing Margin Trade transaction fee estimate

### ISSUE THREAD

**Issue by soulBit** [DistributedCollective/Sovryn-frontend#1391]
"0.00000243 is definitely not enough to close a margin trade
frontend is showing an incorrect estimation of the gas fee when closing margin trading positions"

Tested closing a margin trade, estimated fee was shown as 0.00000244 rBTC

![image](https://user-images.githubusercontent.com/765825/123420669-bf489780-d5b3-11eb-9cb8-e9e39b4fa5c8.png)

Nifty showed max cost as 0.00006 rBTC:
![image](https://user-images.githubusercontent.com/765825/123420727-d38c9480-d5b3-11eb-8f5c-1a67d6c21758.png)

Actual gas cost was:
0.0000293127 rBTC  (488,545 gas used)

The gas limit shown in tx fee estimate is only 40598 which I believe should be using the limit for TxType.CLOSE_WITH_SWAP = 1000000
https://explorer.rsk.co/tx/0x43f28487e6d0a146e713e17cd91ffb5ab376cfcde2f90bcdf741b0550bcf8994

**Comment by soulBit** [comment]
@creed-victor could you add suggested solution to the ticket like you mentioned in standup, and then assign @boltsr

**Comment by grinry** [comment]
TxFeeCalculator calculates gas fee for transaction, however in certain cases it may be wrong (1. fee calculated for tokens that are not approved, but user then approves it in same block. 2. calculated fee becomes invalid because state in the next block changes)

I see two ways for making fix:

1. (easy way) Pass gasLimit to the TxFeeCalculator component `<TxFeeCalculator txConfig={{ gas: gasLimit[TxType.CLOSE_WITH_SWAP] }} />` and change component, so if txConfig.gas prop is set it would use passed value instead calculating it. Note, to get fee you need to multiply gas limit with gas price (`txProps.gas * gas.get()`)

2. (more correct way) Same as 1. but gas should be passed only if user will need to approve his transaction first (check for token allowance).
