### ISSUE TITLE
Three different prices for bitcoin is very confusing (I really don't understand)

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#323]
See:

![Captura de tela de 2021-01-31 16-17-47](https://user-images.githubusercontent.com/1178856/106395306-58e29300-63e0-11eb-84c4-35f20c59d8b8.png)

![Captura de tela de 2021-01-31 16-17-55](https://user-images.githubusercontent.com/1178856/106395310-5c761a00-63e0-11eb-92d3-9a619a8881d8.png)

**Comment by creed-victor** [comment]
Yes, thats because chart takes price from bitfinex exchange, the one in the selector is from oracle that also takes prices from exchanges but not ini the real time.
The one in the dialog is +- actual price you will start a position - which is calculated from our contracts with entered amount. 

We already planing on implementing new data feed for chart so it would show our (correct) price.
Design will also change, so other glitches should be fixed too.
