### ISSUE TITLE
Toggable maintenance mode for frontend

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#415]

**Comment by soulBit** [comment]
@creed-victor I can work on this one, do you have an idea in mind for styling? Maybe just the Sovryn logo and text below it with "Platform is under maintenance, please try again later" - both in center of the page.

We could also get the design team to create some art of a sleeping badger that we can add to the background, but I'm not sure whether that's "professional" enough for the app.

**Comment by creed-victor** [comment]
This one will also require some backend work, you worked with node.js right?

>We could also get the design team to create some art of a sleeping badger that we can add to the background, but I'm not sure whether that's "professional" enough for the app.

Pretty good idea, maybe @t-z-u team can make something?

----

For task itself, there should be multiple type of maintenance:

- [ ] Full maintenance - change entire dapp with that maintenance "badger"
- [ ] Partial maintenance - only show note in each screen with a text

Maintenance mode should be toggle-able from our admin panel, admin signs message, sends it to backend, backend verifies and saves to database.

When user visits dapp, dapp sends request to backend, retrieves maintenance status and if maintenance set then we showing that full maintenance page or only note/ribbon.

I think that when admin set's maintenance he should be able to add optional maintenance message and choose if maintenance is full (disables entire website) or partial.

Currently we have partial maintenance set by .env and which requires redeployment, it prevents users from making new trades and swaps only so I think it would be perfect if when setting partial maintenance admin would be able to choose which services he wants to disable by checking checkboxes:
- Opening Trades & Swaps
- Opening Loans & Borrows
- Closing Trades
- Closing Loans & Borrows
- Adding & Removing AMM liquidity
- ETH bridge and etc.

If all checkboxes are selected it should be still considered as partial maintenance, so users would be able to see all blockchain data there but they will not be able to make new txes.

**Comment by soulBit** [comment]
> you worked with node.js right?

Yep 👍 

Your solution sounds great, but I don't see an admin panel/db in any of the repos, can you give me permissions?

**Comment by t-z-u** [comment]
@soulBit @creed-victor 
can we concentrate on getting the dapp and design system sorted first?
i count lend, borrow, liquidity, new portfolio section, landing page before we have a full product

**Comment by soulBit** [comment]
@creed-victor this is implemented on `feat/maintenance` branches in db & admin repos, and on `feat/maintenance-toggle` branch in this repo.

Three things to note:

- I've allowed separate messages to be set for each "feature" that can have maintenance toggled, since wording a single generic message could get tricky otherwise.

  Db has a new table to store the features that can be toggled, and includes a sample message for each that I used while testing, but these can be reworded as needed. With the exception of full site maintenance, when maintenance is active for a feature, these messages will be applied to relevant buttons in the app via tooltips, in the same way as the current maintenance mode. One potential issue is not having translations for these messages, but I can't see a solution other than having a predefined list to choose from.
- Message that is signed by user to authorize setting maintenance is generic (similar to login auth message). Should this include the maintenance message entered by the user?
- When full site maintenance is enabled and a route other than `/` is accessed, there are a couple of unmounted component state errors that I'm not sure how to debug, could you take a look?
![image](https://user-images.githubusercontent.com/765825/109442661-c2ca7880-7a30-11eb-8592-d1dc6350cc01.png)

**Comment by creed-victor** [comment]
Thanks @soulBit, can you make it as draft PR? It should deploy preview of the feature branch
