### ISSUE TITLE
[YBUG.IO] When clicking trade on main page...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#874]
When clicking trade on main page for lending, am brought to a 404.

*Source url:* https://live.sovryn.app/loans
*Reported by:* 
*Reported at:* 23 Apr at 02:12 UTC

*Location:* CA, Ontario, Kitchener
*Browser:* Chrome 90.0.4430.85

*OS:* macOS 10.15.7
*Screen:* 1440x900
*Viewport:* 1440x692

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/tab5dhgy3zacqq7fd4s0/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkxNDM5NjQsImRhdGEiOnsicmVwb3J0IjoidGFiNWRoZ3kzemFjcXE3ZmQ0czAiLCJ1c2VyIjoiR2l0SHViIn19.n70OBGPMWKQzAhO5pAhboEKIS7mhQwAyZ_A9aWTYoMs)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/tab5dhgy3zacqq7fd4s0](https://ybug.io/dashboard/reports/detail/tab5dhgy3zacqq7fd4s0)

**Comment by soulBit** [comment]
To replicate this, open https://live.sovryn.app/ and click Lending section "Trade" button:
![image](https://user-images.githubusercontent.com/765825/116785540-0a519d00-aa92-11eb-9e8c-1b0a5dd3f369.png)

Button text should be updated to "Lend", and link updated to correct one: https://live.sovryn.app/lend

In addition, the Swap section "Swap" button is using the `?swap` query param in the redirect, but it isn't working - we should adjust this so that it uses the redux state to set swap as active tab, before redirecting to https://live.sovryn.app/trade in the same way as header menu - sample code here: https://github.com/DistributedCollective/Sovryn-frontend/blob/97d25885d1521c1320d0a08fff9c40401daab1e3/src/app/components/Header/index.tsx#L142
