### ISSUE TITLE
[YBUG.IO] Hi- I threw some SOV/RBTC into...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#994]
Hi- I threw some SOV/RBTC into this pool yesterday, and it is not reflected in the "Your current share of the reward pool." Why is that? Thank you very much

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* papalarge@mac.com
*Reported at:* 01 May at 15:03 UTC

*Location:* US, Florida, Palm Beach Gardens
*Browser:* Chrome 90.0.4430.93

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1273x926

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/nrgyzwvpfgwqvjx08xgv/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTk4ODE0MDMsImRhdGEiOnsicmVwb3J0IjoibnJneXp3dnBmZ3dxdmp4MDh4Z3YiLCJ1c2VyIjoiR2l0SHViIn19.rAl4V9L-c3US1tLNIShS1KiKQgQ8ZUvd5SUEQA-4OnI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/nrgyzwvpfgwqvjx08xgv](https://ybug.io/dashboard/reports/detail/nrgyzwvpfgwqvjx08xgv)

**Comment by creed-victor** [comment]
@BetsyBraddock I think this may be a problem with a backend?

**Comment by BetsyBraddock** [comment]
@creed-victor this sounds like an issue with the backend, but it's very difficult to debug without a wallet address. The backend has a bit of a lag because the transaction has to be mined and then it needs to be picked up by the data feed, added to the database and returned to the frontend.

We can definitely implement a better solution (websocket, a spinner on the frontend that shows until the backend picks up the transaction, or we could show the transaction with the word "pending" in the liquidity mining event list while it is being mined and processed by the database), let's talk about it next week

**Comment by soulBit** [comment]
Issue should be resolved by latest Liquidity Mining frontend updates, I'll close this ticket after testing
